MQTT_CONTRACT = {
    "schemaVersion": "1.0",
    "protocolVersion": "MQTT 3.1.1",
    "topicPattern": "factory/dogs/{robotCode}/{channel}",
    "topics": [
        {
            "name": "command",
            "topic": "factory/dogs/{robotCode}/command",
            "direction": "platform_to_device",
            "messageType": "command",
            "qos": 1,
            "retain": False,
            "description": "平台向机器狗下发命令",
        },
        {
            "name": "result",
            "topic": "factory/dogs/{robotCode}/result",
            "direction": "device_to_platform",
            "messageType": "event",
            "qos": 1,
            "retain": False,
            "description": "机器狗向平台回传确认、任务、位置、查询和错误事件",
        },
    ],
    "command": {
        "topic": "factory/dogs/{robotCode}/command",
        "required": [
            "schemaVersion",
            "messageType",
            "commandId",
            "robotCode",
            "traceId",
            "command",
            "issuedAt",
            "source",
            "params",
        ],
        "supportedCommands": ["goto_pose", "stop", "where"],
        "taskCommands": ["goto_pose", "stop"],
        "queryCommands": ["where"],
        "fields": {
            "schemaVersion": "固定 1.0",
            "messageType": "固定 command",
            "commandId": "单次命令唯一 ID",
            "taskId": "任务类命令必填，where 为 null",
            "requestId": "查询类命令必填，任务类为 null",
            "robotCode": "机器狗编码，必须与 Topic 中 {robotCode} 一致",
            "traceId": "链路追踪 ID，result 必须沿用",
            "command": "goto_pose、stop、where",
            "issuedAt": "平台下发时间，ISO 8601",
            "timeoutMs": "超时时间，毫秒",
            "operatorId": "操作人或系统调用方",
            "source": "api、scheduler、agent、system",
            "params": "命令参数对象，不能省略",
        },
        "examples": {
            "goto_pose": {
                "schemaVersion": "1.0",
                "messageType": "command",
                "commandId": "CMD-20260528-000001",
                "taskId": "TASK-20260528-000001",
                "requestId": None,
                "robotCode": "DOG-001",
                "traceId": "TRACE-20260528-000001",
                "command": "goto_pose",
                "issuedAt": "2026-05-28T10:00:00+08:00",
                "timeoutMs": 120000,
                "operatorId": "scheduler",
                "source": "scheduler",
                "params": {
                    "x": 12.34,
                    "y": 56.78,
                    "z": 0,
                    "yaw": 1.57,
                    "mapId": 1,
                    "positionCode": "UNLOAD_POINT_B",
                    "speedLimit": 1.2,
                },
            },
            "where": {
                "schemaVersion": "1.0",
                "messageType": "command",
                "commandId": "CMD-20260528-000003",
                "taskId": None,
                "requestId": "REQ-20260528-000001",
                "robotCode": "DOG-001",
                "traceId": "TRACE-20260528-000002",
                "command": "where",
                "issuedAt": "2026-05-28T10:02:00+08:00",
                "timeoutMs": 8000,
                "operatorId": "scheduler",
                "source": "scheduler",
                "params": {},
            },
        },
    },
    "result": {
        "topic": "factory/dogs/{robotCode}/result",
        "required": [
            "schemaVersion",
            "messageType",
            "event",
            "robotCode",
            "traceId",
            "source",
            "timestamp",
            "data",
        ],
        "events": [
            "command.accepted",
            "command.rejected",
            "task.started",
            "task.succeeded",
            "task.failed",
            "task.stopped",
            "task.timeout",
            "pose.updated",
            "where.result",
            "where.failed",
            "device.offline",
        ],
        "fields": {
            "schemaVersion": "固定 1.0",
            "messageType": "固定 event",
            "event": "标准事件名",
            "eventId": "事件唯一 ID",
            "commandId": "命令相关事件必须携带",
            "taskId": "任务相关事件必须携带",
            "requestId": "查询相关事件必须携带",
            "robotCode": "机器狗编码，必须与 Topic 中 {robotCode} 一致",
            "traceId": "沿用 command.traceId",
            "source": "设备回传固定 device",
            "timestamp": "事件发生时间，ISO 8601",
            "data": "事件数据对象",
            "error": "错误对象，无错误时为 null",
        },
        "errorCodes": [
            "DEVICE_BUSY",
            "INVALID_TARGET_POSE",
            "NAVIGATION_NO_PATH",
            "NAVIGATION_BLOCKED",
            "LOW_BATTERY",
            "COMMAND_ACK_TIMEOUT",
            "TASK_TIMEOUT",
            "STOP_FAILED",
            "DEVICE_OFFLINE",
            "MQTT_BROKER_UNAVAILABLE",
            "WHERE_FAILED",
        ],
    },
}
